# Generated by Django 5.2.7 on 2025-12-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_bookshelf_delete_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
