# Generated by Django 5.2.7 on 2025-12-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_category_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(related_name='books', to='app.bookshelf'),
        ),
    ]
